Fix 1
100roj/BoCSDB pull request #1
Opened 2021-06-10 16:08 UTC by 100roj

-Переработал запросы и таблицы
-Исправил ERD
-Исправил Отчёт

2021-06-22 13:20 UTC, MarinaPaley requested changes

2021-06-22 13:20 UTC, MarinaPaley commented on Create Tables/CreateTable2.sql
> +CREATE TABLE IngList(
У этой таблицы нет первичного ключа? Остальные поля - внешние ключи?

2021-06-22 13:20 UTC, MarinaPaley commented on Create Tables/CreateTable5.sql
> +CREATE TABLE StoreList(
Тоже, как и с Table 2

2021-06-25 09:32 UTC, 100roj commented on Create Tables/CreateTable2.sql
> +CREATE TABLE IngList(
Эти таблицы обозначают связь "Многие ко многим". Им обязательно нужны первичные ключи?

2021-06-30 16:44 UTC, MarinaPaley approved these changes

2021-06-30 19:12 UTC, merged