Develop
100roj/BoCSDB pull request #2
Opened 2021-10-12 15:41 UTC by 100roj

Добавил лабораторные работы

2021-10-13 11:41 UTC, MarinaPaley reviewed
я же просила с заданием в виде коментариев перед каждым запросом

2021-10-18 17:19 UTC, MarinaPaley reviewed
а какой вариант Вы делали?
Где Вы взяли задания?

2021-10-18 17:19 UTC, MarinaPaley commented on Lab1/4-6.sql
> +﻿/*Переписать запрос таким образом, чтобы поиск проходил по всем строкам LastName, начинающимся на ‘Mac’с использованием функции SUBSTRING().*/
ну, не `substring()`...

2021-11-02 09:13 UTC, MarinaPaley requested changes

2021-11-02 09:13 UTC, MarinaPaley commented on Lab1/1.sql
> +﻿/*Показать все поля из таблицы Production.Document.*/
скрипт не соответсвует заданию

2021-11-02 09:13 UTC, MarinaPaley commented on Lab1/2.sql
> +﻿/*Показать поля ProductID, DocumentNode из таблицы Production.ProductDocument.*/
скрипт не соответсвует заданию

2021-11-02 09:13 UTC, MarinaPaley commented on Lab1/3+4.sql
> +﻿/*Показать поля ProductID,BusinessEntityID, AverageLeadTime, StandardPrice из таблицы Purchasing.ProductVendor, где средний промежуток времени (в днях) между размещением заказа у продавца и получени
скрипт не соответсвует заданию

2021-11-02 09:13 UTC, MarinaPaley commented on Lab3/1.sql
> +/*Ïîêàçàòü íîìåðà àêêàóíòîâ (AcCountNumber) è ïîëÿ FirstName, LastName èç òàáëèö Person.Person, Sales.Customer.*/
кодировка не UTF-8

2021-11-12 14:44 UTC, MarinaPaley requested changes
Показана чужая работа. У Вас по списку другой вариант.

2021-11-26 21:29 UTC, MarinaPaley requested changes

2021-11-26 21:29 UTC, MarinaPaley commented on Lab2/2.sql
> +Where PasswordSalt Not Like '%[q, w, e, r, t, y]%'
он не работает
![100roj](https://user-images.githubusercontent.com/26978698/143655806-0658b078-74b7-4dd7-b4c0-df8950097856.jpg)

2021-11-26 21:29 UTC, MarinaPaley commented on Lab2/4.sql
> +SELECT *
Нужно найти количество.

2021-11-26 21:29 UTC, MarinaPaley commented on Lab2/5.sql
> +﻿/*5. Вывести ProductID из таблицы Production.ProductListPriceHistory  у которых суммарная цена (ListPrice) больше 50. Добавить столбец с рангом, определяя его порядок в зависимости от количества стр
Где оограничение на суммарную цену?

2021-11-26 21:29 UTC, MarinaPaley commented on Lab3/8.sql
> +﻿/*8. Показать список BusinessEntityID, которые содержатся и в таблице Person.Person, и в таблице HumanResources.EmployeePayHistory*/
неправильно, нужно и там, и там

2021-11-27 13:22 UTC, 100roj commented on Lab3/8.sql
> +﻿/*8. Показать список BusinessEntityID, которые содержатся и в таблице Person.Person, и в таблице HumanResources.EmployeePayHistory*/
А разве если у нас имя есть в одной таблице, оно же будет и в другой?

2021-11-27 13:23 UTC, 100roj commented on Lab2/2.sql
> +Where PasswordSalt Not Like '%[q, w, e, r, t, y]%'
Работает. Внизу вывод всех строк, он мне нужен был для отладки, я просто забыл его исправить

2021-12-06 12:00 UTC, MarinaPaley approved these changes

2021-12-07 10:01 UTC, merged